import UserRepoStats from './UserRepoStats';

// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

1
export default interface PieChartContributionsVM {
	avatar_url: string;
	contributions: number;
	login: string;
	modifications: UserRepoStats;
	total: number;
};
